package com.jiangshui.springbootpractic.mapper.config;

public interface userStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    int insert(userStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    int insertSelective(userStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    userStudent selectByPrimaryKey(Integer id);
}