package com.jiangshui.springbootpractic.model;

public class userStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.id
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.name
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.age
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.id
     *
     * @return the value of user_student.id
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.id
     *
     * @param id the value for user_student.id
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.name
     *
     * @return the value of user_student.name
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.name
     *
     * @param name the value for user_student.name
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.age
     *
     * @return the value of user_student.age
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.age
     *
     * @param age the value for user_student.age
     *
     * @mbg.generated Thu Jun 28 16:52:19 GMT+08:00 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}