


spring:
    datasource:
        url: jdbc:mysql://shui:3306/springbootpractice
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

#注解，无配置
mybatis:
    type-aliases-package: com.jiangshui.springbootpractic.model
    configuration:
      map-underscore-to-camel-case: true


#配置
#mybatis:
#    type-aliases-package: com.jiangshui.springbootpractic.model
#    mapper-locations: com.jiangshui.springbootpractic.mapper
#    configuration:
#        map-underscore-to-camel-case: true

